### ISSUE TITLE
Update questionnaire flow

### ISSUE THREAD

**Issue by ir4y** [beda-software/fhir-emr#13]
A user can create a new questionnaire.
Initially, it was planned to use a kind of FormBuilder http://localhost:3000/questionnaires/builder
I would like to replace FormBuilder with a solution based on SDC IDE.

- [x] Change Edit behaviour
<img width="1280" alt="Screenshot 2022-07-27 at 11 40 29" src="https://user-images.githubusercontent.com/1488983/181216227-4e01be54-12eb-4cfb-b2d4-e897f4ff8310.png">

- [ ] Change add questinnaire behaviour
<img width="1280" alt="Screenshot 2022-07-27 at 11 41 27" src="https://user-images.githubusercontent.com/1488983/181216401-168066cd-d276-4713-9b1f-0260dc5cfa97.png">

**Comment by pavlushkin** [comment]
Done
