### ISSUE TITLE
Update Appointment status after launching Encounter

### ISSUE THREAD

**Issue by m0rl** [beda-software/fhir-emr#132]
When an Encounter is launched, the status of the corresponding Appointment should automatically change to reflect that the Encounter has started. However the Appointment status is always "booked" and doesn't change.

**Comment by vesnushka** [comment]
<img width="1116" alt="Screenshot 2023-05-23 at 11 40 24" src="https://github.com/beda-software/fhir-emr/assets/11814124/d1bcf2d0-1596-4964-8067-b25d8a6f74b4">

**Comment by vesnushka** [comment]
<img width="1148" alt="Screenshot 2023-05-23 at 11 41 19" src="https://github.com/beda-software/fhir-emr/assets/11814124/33cb8b7c-8726-4299-a934-105d079cebca">

**Comment by dmitryashutov** [comment]
Fixed
