### ISSUE TITLE
Fix translations

### ISSUE THREAD

**Issue by oksana-shchukina** [beda-software/fhir-emr#171]
Link to the document https://emr.beda.software/patients/f618950f-4148-4ea6-a3f3-357a67aee1ac/encounters/36b4c414-6693-4a97-9704-b5a2ccfdfb82/e317a5f8-03f8-4a89-aacb-71b2ccbd9a3f/history

![Image](https://github.com/beda-software/fhir-emr/assets/138698468/6dfde5b2-bf35-46aa-810e-56a4b3d4537d)

**Comment by ir4y** [comment]
- [ ] Check why the English test is not used as a default
- [ ] If it is not possible add recommit check that prevents committing untranslated texts
