### ISSUE TITLE
Prepare demo data for staging

### ISSUE THREAD

**Issue by oksana-shchukina** [beda-software/fhir-emr#178]

**Comment by oksana-shchukina** [comment]
We can Ask Alex to help

**Comment by projkov** [comment]
@oksana-shchukina Could you provide any details about this issue? What kind of demo data do you want to add?

**Comment by oksana-shchukina** [comment]
@projkov We wanted to prepare some data that looks like real data: to create practitioners, to fill in the timetable, to create patients and etc. It can help to test the system in a better way.
