### ISSUE TITLE
Search text is not readable

### ISSUE THREAD

**Issue by ir4y** [beda-software/fhir-emr#196]
In dark theme, the search text in select is too dark.
<img width="784" alt="Screenshot 2023-10-13 at 13 52 43" src="https://github.com/beda-software/fhir-emr/assets/1488983/164f9e4c-e38c-4272-94da-5e462c4cd08a">

**Comment by tmatheas** [comment]
@ir4y Can you assign this issue to me ? Also can you add `Hacktoberfest` label to it ?

**Comment by ir4y** [comment]
@tmatheas you are welcome.

**Comment by VivekChatterjee** [comment]
Hey @tmatheas are you still working on this issue?

**Comment by tmatheas** [comment]
> Hey @tmatheas are you still working on this issue?
> 

Yes @VivekChatterjee

**Comment by VivekChatterjee** [comment]
Cool

**Comment by tmatheas** [comment]
@VivekChatterjee I was unable to setup the repo in my machine. You can start working on this task if you wish

**Comment by ir4y** [comment]
@tmatheas I am sorry to hear that you can't run the app in the dev mode.
Could you please share your feedback or maybe report an issue you faced?
