### ISSUE TITLE
Fix the output of the practitioner's names which is created via Syntea in the encounter list component 

### ISSUE THREAD

**Issue by projkov** [beda-software/fhir-emr#197]
Use https://docs.aidbox.app/api-1/bulk-api-1/synthea-by-bulk-api#load-by-resource-type tutorial to load Syntea demo data

In general fhir-emr used PractitionerRole in the Encounter.participant* attribute. In the Syntea data for the participant in the encounter used Practitioner resource reference.

**Comment by Sairajepawar** [comment]
i would like to look into this issue, so pls assign this issue to me

**Comment by ir4y** [comment]
you are welcome @Sairajepawar

**Comment by Sairajepawar** [comment]
things i have concluded according to my research:-

Synthea is an open-source patient generation tool which generates synthetic but realistic patient data associated with health records covering every aspect of healthcare.

Aidbox is backend platform specifically tailored for healthcare applications and is built around the Fast Healthcare Interoperability Resources (FHIR) standard

I went through a tutorial, regarding generation of data from synthea and how to adjust the properties of the data.

But i don’t understand the issue you have posted, can please explain it in detail.

**Comment by projkov** [comment]
> things i have concluded according to my research:-
> 
> Synthea is an open-source patient generation tool which generates synthetic but realistic patient data associated with health records covering every aspect of healthcare.
> 
> Aidbox is backend platform specifically tailored for healthcare applications and is built around the Fast Healthcare Interoperability Resources (FHIR) standard
> 
> I went through a tutorial, regarding generation of data from synthea and how to adjust the properties of the data.
> 
> But i don’t understand the issue you have posted, can please explain it in detail.

Hello, @Sairajepawar 
Currently, we show practitioner's name if one of the Encounter.participant is a reference to the PractitionerRole resource.
We want to support showing the practitioner's name if one of the Encounter.participant is a reference to the Practitioner resource (this one is used in the Syntea data)
Both of these variants are correct according to the [FHIR r4 specification](https://hl7.org/fhir/R4/encounter.html).

In general, this issue includes changes in the get request for Encounter data in the EncounterList component.

Hope this information will be helpful to you. Thank you for your time.

**Comment by projkov** [comment]
@Sairajepawar Hello, how are you? I hope you are doing well.
I want to show you code fixes for this issue. I think it can be helpful if you have started to learn programming. There is a commit with code changes: https://github.com/beda-software/fhir-emr/commit/1a78113c29bca60ab7e163d8e9fbe4caa9321635

The main changes are:
1. Updated request to the server: we want to include Practitioner resources that can be present in Encounter.participant.individual according to the FHIR specification;
2. New method to get a practitioner. In this method, the system will get practitioner conditionally. If an individual is PractitionerRole we should find a Practitioner resource through PractitionerRole.practitioner. If an individual is a Practitioner we just need to filter by this practitioner. 

I hope it will be helpful for you. Happy coding and a nice day.

**Comment by projkov** [comment]
The problem was fixed. Changes are deployed to the production environment. The issue can be closed.
<img width="1552" alt="Screenshot 2023-11-22 at 16 19 13" src="https://github.com/beda-software/fhir-emr/assets/4172228/8b1e502c-5347-4789-8f97-53cc23c8550d">
