### ISSUE TITLE
Implement document amendment

### ISSUE THREAD

**Issue by dymio** [beda-software/fhir-emr#20]
- [x] Once a document is saved in `completed` and extracted a [provenance](https://www.hl7.org/fhir/provenance.html) resource should be created. Please check https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/Extraction.20and.20Provenance
- [x] A user may request an amendment, in this case, information from provenance is used to delete previously extracted resources and extract data one more time. In this case, the start status should be `amended`.
- [x] Add a history page for amended documents that allow to browse through all previous versions. 
- [x] Show all the resources on the patient overview page as links which lead to the source questionnaire response page

**Comment by ir4y** [comment]
Aidbox specific queries for Provenance
```
query: >-
  select resource from provenance where
  knife_extract_text(resource,'[["entity","what","uri"]]'),'') like
  {{params.target}}
params:
  target:
    type: string
    format: '%%%s%%'
    isRequired: true
id: provenance-by-source
resourceType: AidboxQuery
​```

```
query: >-
  select resource from provenance where
  array_to_string(knife_extract_text(resource,'[["target","uri"]]'),'') like
  {{params.target}}
params:
  target:
    type: string
    format: '%%%s%%'
    isRequired: true
id: provenance-by-target
resourceType: AidboxQuery
```
