### ISSUE TITLE
Generalize helper scripts

### ISSUE THREAD

**Issue by ir4y** [beda-software/fhir-emr#207]
Now the app uses makefile and a bunch of sh scripts.
We need to generalize it and use one approach.
It could be one Makefile, one sh script, or any other solution like 
- https://github.com/go-task/task
-  https://github.com/pyinvoke/invoke etc.

**Comment by projkov** [comment]
@ir4y MR is available here:
https://github.com/beda-software/fhir-emr/pull/212/files
