### ISSUE TITLE
Error while creating an Encounter for generated patient

### ISSUE THREAD

**Issue by maximpetov** [beda-software/fhir-emr#211]
Steps to reproduce:
1. On the Encounters page click on the Open button
2. If encounter has a "completed" status, go to the Overview tab and then go back to the Encounters tab
3. Click on the "Create Encounter" button

Error message:
`Error: "%Patient.name.given[0] + ' ' + %Patient.name.family" - Cannot ['Kaye394 '] + [<fhirpathpy.engine.nodes.ResourceNode object at 0x7f88080bd050>, <fhirpathpy.engine.nodes.ResourceNode object at 0x7f88080bca90>] (invalid)`

![error](https://github.com/beda-software/fhir-emr/assets/6428960/f88a5825-c6e7-4d75-90a6-8d032d1ae5e0)

**Comment by projkov** [comment]
This problem also can be reproduced in these Questionnaires:

Allergies
GAD7
Immunization
Medication
PHQ-2/PHQ-9 Depression Screening
Vitals

Problem related to the name of the patient. Patients from Syntea have 2 names.
