### ISSUE TITLE
Conditions are not ordered by date

### ISSUE THREAD

**Issue by ir4y** [beda-software/fhir-emr#215]
<img width="588" alt="Screenshot 2023-11-27 at 16 47 45" src="https://github.com/beda-software/fhir-emr/assets/1488983/592df374-ee4f-415e-8d93-948b3daa0b0d">
The same issue for other information on the dashboard and resource list
<img width="1179" alt="Screenshot 2023-11-27 at 16 48 27" src="https://github.com/beda-software/fhir-emr/assets/1488983/c7c41212-d4a8-40d4-b59f-97937c207600">

**Comment by projkov** [comment]
For the output, we use recordedDate or createdAt.
recordedDate is filled in all condition resources that we get from Syntea. Maybe we should create recordedDate for Conditions in our mappers?
