### ISSUE TITLE
Display activity ring for past 7 days 

### ISSUE THREAD

**Issue by ir4y** [beda-software/fhir-emr#223]
It seems that we display information for the current week, not for the last 7 days. 
<img width="593" alt="Screenshot 2023-12-04 at 16 05 09" src="https://github.com/beda-software/fhir-emr/assets/1488983/bde4e3c2-2cce-40cc-b70c-9c62a1c786c0">

**Comment by projkov** [comment]
@ir4y looks like everything is good. Could you provide the patient's ID with the incorrect display of activity rings?
I made fake data for patient1 and you can see, that all works correctly.
https://emr.beda.software/patients/patient1

Maybe this issue can be related to the problem with synchronization, not display
