### ISSUE TITLE
Fix invoices layout

### ISSUE THREAD

**Issue by atuonufure** [beda-software/fhir-emr#295]
Mobile version of the invoices page is displayed incorrectly

![image](https://github.com/user-attachments/assets/5c93809b-ed6e-485e-b396-432226e625a9)

For example, practitioner page

![image](https://github.com/user-attachments/assets/fa69dc54-2064-446d-bd9e-196cb9f25841)

Looks like at a minimum the header and filters should look correct

**Comment by ryo-kozin** [comment]
@atuonufure 
Hi, I found this issue while searching for `Good First Issues` on GitHub and would love to work on it. Is it okay if I take this on?

Thank you!

**Comment by atuonufure** [comment]
> Hi @atuonufure,
> 
> I found this issue while searching for Good First Issues on GitHub and would love to contribute to it. I wanted to check if this project is open for contributions from external developers. If it is, I'd be happy to start working on this issue.
> 
> Looking forward to your response!
> 
> Thank you!

Hi!
You can try, but note that the config should be copied now like this
`cp contrib/emr-config/config.local.js contrib/emr-config/config.js`
The rest of the information in the documentation is up to date

**Comment by ryo-kozin** [comment]
Thank you for the confirmation, @atuonufure!

I'll go ahead and set up the environment using the updated config instructions. I'll keep an eye on the documentation and proceed with the issue accordingly.

If I run into any questions, I'll reach out. Thanks for your guidance!

Looking forward to contributing.

**Comment by ryo-kozin** [comment]
Hi @atuonufure,

I have created a pull request (#300) to address the layout issues mentioned in this issue (#295). The following changes were made to improve the mobile responsiveness of the invoices page:

- Horizontal scroll added: Implemented horizontal scrolling in the InvoiceList table to ensure the content is viewable on smaller screens.
- Responsive adjustments: Updated the InvoiceListSearchBar to use flex-wrap: wrap; to make sure the search filters align correctly on mobile devices.

These changes should resolve the layout problems on the mobile version of the invoices page. Please review the pull request when you have a chance, and let me know if there are any additional changes or improvements needed.

Looking forward to your feedback!

Thank you!

**Comment by atuonufure** [comment]
Hi @ryo-kozin!
Thank you for your contribution and information about the other routes
