### ISSUE TITLE
Facing an error while setting up the project locally.

### ISSUE THREAD

**Issue by ShashankJ017** [beda-software/fhir-emr#324]
![image](https://github.com/user-attachments/assets/67f6a65b-524b-4e80-9037-c82b026e1072)

**Comment by ir4y** [comment]
Thank you @ShashankJ017 
The documentation was not updated properly after the recent refactoring.
Please run this command to create a configuration file that is missing
```
cp contrib/emr-config/config.local.js contrib/emr-config/config.js
```

**Comment by ir4y** [comment]
This section of the documentation https://github.com/beda-software/emr-documentation/blob/main/docs/Welcome/getting-started.md#prepare-frontend-configuration should be updated to match all recent updates mentioned here:
https://docs.emr.beda.software/Developers%20Guide/custom-emr-build#quick-start-guide

**Comment by daregoodness1997** [comment]
![beda emr error](https://github.com/user-attachments/assets/cac1c6a1-1d7a-4757-8856-7ecd6df5d109)
I get this error when i open any form modal, I am not sure what could be causing that @ir4y

**Comment by ir4y** [comment]
Hi @daregoodness1997 Could you please create a separated issue since your error is not related to the original one.
Also, please provide aidbox and fhir-sdc container logs in the new issue.

Best, Ilya

**Comment by ir4y** [comment]
Documentation has been updated.
