### ISSUE TITLE
Fix patient birth date input

### ISSUE THREAD

**Issue by dymio** [beda-software/fhir-emr#41]
Make the input of entering birth date in the patient form work normal (see the video included).

https://user-images.githubusercontent.com/1663746/213120103-1d1428c5-4a10-4410-99e0-32e37f912a1c.mov

Also, restrict the input from entering a future date.

**Comment by dmitryashutov** [comment]
@qscgyjqscgyj please pull master and check one more time this issue. It might be fixed during the #31

**Comment by qscgyjqscgyj** [comment]
Fixed in https://github.com/beda-software/fhir-emr/commit/24ddb2f74e5f56e0fd17506dca7bdd4274bf3b06
