### ISSUE TITLE
Scheduling

### ISSUE THREAD

**Issue by dymio** [beda-software/fhir-emr#55]
Leverage https://github.com/beda-software/aidbox-scheduling-node-app

**Comment by dymio** [comment]
https://github.com/beda-software/aidbox-scheduling-node-app
focus on `scheduling-node-app` and `scheduling-react-app`.

In https://github.com/beda-software/aidbox-scheduling-node-app/tree/main/scheduling-react-app/src is where scheduling components are placed. `/ScheduleCalendar/` for records, `/UsualSchedule/` for slots publication.

**Comment by atuonufure** [comment]
Appointment creation currently does not work in the deployed version of the application
