### ISSUE TITLE
Patient dashboard

### ISSUE THREAD

**Issue by dymio** [beda-software/fhir-emr#56]
Add the patient dashboard according to [the design](https://www.figma.com/file/2bxMDfG3lRPEZpRwDC4gTB/SaaS-EMR-System?node-id=135823%3A205938&t=6jhJ0SoGBKi5yWmd-4) ("Patient / Overview" screen).

BMI = weight / height<sup>2</sup>, where weight in kg and height im meters, or weight in pounds and height in inches.

Take:

- conditions from ["Condition" resource](https://www.hl7.org/fhir/condition.html).
- medications from ["MedicationStatement" resource](https://www.hl7.org/fhir/medicationstatement.html) or ["MedicationRequest" resource](https://www.hl7.org/fhir/medicationrequest.html) (please get a consultation and decide).
- allergies from ["AllergyIntolerance" resource](https://www.hl7.org/fhir/allergyintolerance.html).
- immunizations from ["Immunization" resource](https://www.hl7.org/fhir/immunization.html).

**Comment by vesnushka** [comment]
Moved BMI part to separate issue https://github.com/beda-software/fhir-emr/issues/59
