### ISSUE TITLE
Display BMI on Patient Overview

### ISSUE THREAD

**Issue by vesnushka** [beda-software/fhir-emr#59]
[The design](https://www.figma.com/file/2bxMDfG3lRPEZpRwDC4gTB/SaaS-EMR-System?node-id=135823%3A205938&t=6jhJ0SoGBKi5yWmd-4) ("Patient / Overview" screen).

`BMI = weight / height ^ 2`, where weight in kg and height im meters, or weight in pounds and height in inches.

Need to finish Vitals form and vitals extract to get these values

**Comment by dymio** [comment]
Do after https://github.com/beda-software/fhir-emr/issues/67

**Comment by atuonufure** [comment]
https://github.com/beda-software/fhir-emr/pull/72
