### ISSUE TITLE
Vitals form

### ISSUE THREAD

**Issue by dymio** [beda-software/fhir-emr#67]
Make a form by [design](https://www.figma.com/file/2bxMDfG3lRPEZpRwDC4gTB/SaaS-EMR-System?node-id=135823%3A206923&t=8EnpLwP7qAYN9FF6-0)

**Comment by qscgyjqscgyj** [comment]
Vitals form extraction example: https://github.com/Aidbox/sdc-forms-library/blob/main/zrc/aidbox/forms/vitals.edn

**Comment by qscgyjqscgyj** [comment]
- [ ] Add patient's height info population in `vitals-create` questionnaire from previous `vitals-create` questionnaire responses
