### ISSUE TITLE
UI updates

### ISSUE THREAD

**Issue by ir4y** [beda-software/fhir-emr#73]
- update login page, add demo login and password
- integrate chatra widget
- add footer
- add google analytics tag

**Comment by maximpetov** [comment]
**Add footer**
Made with ❤ by Beda Software. Design is [here](https://www.figma.com/file/2bxMDfG3lRPEZpRwDC4gTB/Beda-EMR?node-id=136198%3A211941&t=wwUhVYjneH6yeEac-1) Beda Software is a link, and it should lead to the https://beda.software/emr

**Update login page, add demo login and password**
Add a hint with credentials to the login page. Design is [here](https://www.figma.com/file/2bxMDfG3lRPEZpRwDC4gTB/Beda-EMR?node-id=136202%3A212134&t=wwUhVYjneH6yeEac-1).

Google Analytics code
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-11071319885"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-11071319885');
</script>
```

Chatra widget code
```
<!-- Chatra customisation -->
<script>
window.ChatraSetup = {
    colors: {
        buttonText: '#1E2939', /* chat button text color */
        buttonBg: '#FBE357'    /* chat button background color */
    }
};
</script>
<!-- /Chatra customisation -->
<!-- Chatra {literal} -->
<script>
    (function(d, w, c) {
        w.ChatraID = 'QB8pfsQK6GAkyPfTH';
        var s = d.createElement('script');
        w[c] = w[c] || function() {
            (w[c].q = w[c].q || []).push(arguments);
        };
        s.async = true;
        s.src = 'https://call.chatra.io/chatra.js';
        if (d.head) d.head.appendChild(s);
    })(document, window, 'Chatra');
</script>
<!-- /Chatra {/literal} -->
```

**Comment by dymio** [comment]
Thanks @maximpetov , I have no questions and take this issue in development.

**Comment by dymio** [comment]
Issues to make all the discussed before:

- add footer https://github.com/beda-software/fhir-emr/issues/76
- update login page, add demo login and password https://github.com/beda-software/fhir-emr/issues/77
- add google analytics tag https://github.com/beda-software/fhir-emr/issues/78
- integrate chatra widget https://github.com/beda-software/fhir-emr/issues/79

I am closing this issue. If there is something more to discuss or design, please reopen it.
