### ISSUE TITLE
Thank you page

### ISSUE THREAD

**Issue by dymio** [beda-software/fhir-emr#80]
Add a new page to redirect a user after filling in a shared questionnaire. Let's call it "Thank you" page.

We have a feature of shared forms available by a link. Anyone who has that link can access it and fill it in. Right now, after filling in a shared form, a user redirects to a login page. But we have no flow to log in a patient, so this redirect is useless and even confusing. This is the reason why we need a "thank you" page to redirect users after filling in a shared questionnaire.

**Comment by dymio** [comment]
@maximpetov please think about a design for this feature. Reach me if you have questions.

**Comment by maximpetov** [comment]
@dymio Is any additional text required on this page? Something like this: "Thank you for filling out the questionnaire. Now you can close this page". Maybe you have something else to add.

**Comment by Galuev** [comment]
Design:
https://www.figma.com/file/AYiUwPUFf4z2MfC7iIT46Q/%5BLegacy%5D-Beda-EMR?node-id=1%3A216467&t=aPiCVHlAj3YCwvPm-4

**Comment by ir4y** [comment]
it seems that we have a regression and this page is not showing anymore.
